# Generated by Django 2.2.13 on 2020-06-22 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_message'),
        ('dating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='berkeley',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_berkeley', to='home.CustomText'),
        ),
    ]
